server:
  port: 8104

spring:
  application:
    name: shipment-service
  mongodb:
    uri: #fill
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method